version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - films-app
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../postgresql/pg_data:/var/lib/postgresql/data
      - ../postgresql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - mongo.env
    networks:
      - films-app
    ports:
      - 27017:27017
    volumes:
      - ../mongo/data/db:/data/db
      - ../mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  nginx:
    image: nginx:latest
    ports:
      - '8001:80'
    restart: always
    volumes:
      - ../media-content:/usr/share/nginx/html

  backend:
    image: ${DOCKER_REGISTRY-}xmas-api
    restart: always
    build:
      context: ../backend/FilmsApp.WebApi
      dockerfile: FilmsApp.WebApi/Dockerfile
    networks:
      - films-app
    ports:
      - '8155:80'

networks:
  films-app:
    driver: bridge
